export type Item = {
	title: string;
	file: string;
	subTitle: string;
}
export type List = {
	list: Array<Item>;
}

export default {
	list: [{
		title: '普通模式演示',
		file: 'common-demo',
		subTitle: ''
	},{
		title: '自定义下拉刷新演示',
		file: 'custom-demo',
		subTitle: ''
	},{
		title: '滑动切换选项卡演示',
		file: 'swiper-demo',
		subTitle: ''
	},{
		title: '下拉刷新显示最后更新时间演示',
		file: 'show-update-time-demo',
		subTitle: ''
	}]
} as List
